# Generated by Django 6.0.3 on 2026-03-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='code',
            new_name='dcode',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='code',
            new_name='ecode',
        ),
    ]
